require "bundler/gem_tasks"
require "rspec/core/rake_task"
# require 'rcov/rcovtask'
require "yard"

desc "Run specs"
RSpec::Core::RakeTask.new do |t|
  t.pattern = "spec/**/*_spec.rb"
end

desc "Run specs with coverage"
RSpec::Core::RakeTask.new("spec_rcov") do |t|
  t.pattern = "spec/**/*_spec.rb"
  t.rcov = true
  t.rcov_opts = %w{--exclude spec,gems}
  t.rcov_opts << %[-o "coverage"]
end

# RSpec::Rake::SpecTask.new("rcov_spec") do |t|
#   t.spec_files = FileList['spec/**/*_spec.rb']
#   t.spec_opts = ['--color']
#   t.rcov = true
#   t.rcov_opts = ['--exclude', '^spec,/gems/']
# end

# desc 'Performs code coverage.'
# Rcov::RcovTask.new do |t|
#   t.test_files = FileList['spec/*_spec.rb']
#   t.verbose = true
# end

# desc "Clean files generated by rake tasks"
# task :clobber => [:clobber_rcov]

YARD::Rake::YardocTask.new do |t|
end

task :default => :spec